/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DateButton {
        /**
          * data to emit
         */
        "data": string;
    }
    interface DateOutput {
    }
    interface InitDate {
    }
}
declare global {
    interface HTMLDateButtonElement extends Components.DateButton, HTMLStencilElement {
    }
    var HTMLDateButtonElement: {
        prototype: HTMLDateButtonElement;
        new (): HTMLDateButtonElement;
    };
    interface HTMLDateOutputElement extends Components.DateOutput, HTMLStencilElement {
    }
    var HTMLDateOutputElement: {
        prototype: HTMLDateOutputElement;
        new (): HTMLDateOutputElement;
    };
    interface HTMLInitDateElement extends Components.InitDate, HTMLStencilElement {
    }
    var HTMLInitDateElement: {
        prototype: HTMLInitDateElement;
        new (): HTMLInitDateElement;
    };
    interface HTMLElementTagNameMap {
        "date-button": HTMLDateButtonElement;
        "date-output": HTMLDateOutputElement;
        "init-date": HTMLInitDateElement;
    }
}
declare namespace LocalJSX {
    interface DateButton {
        /**
          * data to emit
         */
        "data"?: string;
        /**
          * event to emit
         */
        "onEmitDate"?: (event: CustomEvent<String>) => void;
    }
    interface DateOutput {
    }
    interface InitDate {
    }
    interface IntrinsicElements {
        "date-button": DateButton;
        "date-output": DateOutput;
        "init-date": InitDate;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "date-button": LocalJSX.DateButton & JSXBase.HTMLAttributes<HTMLDateButtonElement>;
            "date-output": LocalJSX.DateOutput & JSXBase.HTMLAttributes<HTMLDateOutputElement>;
            "init-date": LocalJSX.InitDate & JSXBase.HTMLAttributes<HTMLInitDateElement>;
        }
    }
}
